# Generated by Django 4.2.7 on 2023-12-05 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.CharField(blank=True, max_length=512, null=True)),
                ('x_pos', models.IntegerField(default=0, help_text='divided by 1000 will be mission-unit position')),
                ('y_pos', models.IntegerField(default=0, help_text='divided by 1000 will be mission-unit position')),
                ('z_pos', models.IntegerField(default=0, help_text='divided by 1000 will be mission-unit position')),
                ('x_ori', models.SmallIntegerField(default=0, help_text='mission-unit rotation 0-360*')),
                ('y_ori', models.SmallIntegerField(default=0, help_text='mission-unit rotation 0-360*')),
                ('z_ori', models.SmallIntegerField(default=0, help_text='mission-unit rotation 0-360*')),
                ('mcu_objects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_parent', to='core.baseobject')),
                ('mcu_targets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_parent', to='core.baseobject')),
            ],
        ),
    ]
