# Generated by Django 4.2.7 on 2023-12-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(help_text='mission name is not used in .Mission file itself, but it helps searcing missions', max_length=256)),
                ('lc_name', models.PositiveIntegerField()),
                ('lc_desc', models.PositiveIntegerField()),
                ('lc_author', models.PositiveIntegerField()),
                ('mission_time', models.PositiveIntegerField()),
                ('mission_properties', models.JSONField(max_length=1024)),
                ('wind_layers', models.JSONField(max_length=256)),
                ('countries', models.JSONField(max_length=256)),
            ],
        ),
    ]
