# Generated by Django 4.2.7 on 2023-12-05 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseobject',
            name='mcu_objects',
        ),
        migrations.RemoveField(
            model_name='baseobject',
            name='mcu_targets',
        ),
        migrations.AlterField(
            model_name='baseobject',
            name='x_ori',
            field=models.SmallIntegerField(default=0, help_text='mission-unit rotation 0-360*', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(359)]),
        ),
        migrations.AlterField(
            model_name='baseobject',
            name='y_ori',
            field=models.SmallIntegerField(default=0, help_text='mission-unit rotation 0-360*', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(359)]),
        ),
        migrations.AlterField(
            model_name='baseobject',
            name='z_ori',
            field=models.SmallIntegerField(default=0, help_text='mission-unit rotation 0-360*', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(359)]),
        ),
        migrations.AddField(
            model_name='baseobject',
            name='mcu_objects',
            field=models.ManyToManyField(blank=True, null=True, related_name='object_parent', to='core.baseobject'),
        ),
        migrations.AddField(
            model_name='baseobject',
            name='mcu_targets',
            field=models.ManyToManyField(blank=True, null=True, related_name='target_parent', to='core.baseobject'),
        ),
    ]
