# Generated by Django 4.2.7 on 2023-12-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_baseobject_mcu_objects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseobject',
            name='mcu_objects',
            field=models.ManyToManyField(blank=True, related_name='object_parent', to='core.baseobject'),
        ),
        migrations.AlterField(
            model_name='baseobject',
            name='mcu_targets',
            field=models.ManyToManyField(blank=True, related_name='target_parent', to='core.baseobject'),
        ),
        migrations.AlterField(
            model_name='baseobject',
            name='x_pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseobject',
            name='y_pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseobject',
            name='z_pos',
            field=models.IntegerField(default=0),
        ),
    ]
