# Generated by Django 4.2.7 on 2023-12-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_missionoptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MissionOptions',
            new_name='Mission',
        ),
    ]
