# Generated by Django 4.2.7 on 2023-12-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_missionoptions_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_date',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
