# Generated by Django 4.2.7 on 2023-12-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mission_mission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_objects',
            field=models.ManyToManyField(blank=True, related_name='attached_mission', to='core.missionobject'),
        ),
    ]
