# Generated by Django 4.2.7 on 2024-01-20 17:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mission_mission_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionobject',
            name='object_type',
            field=models.CharField(choices=[('OPTIONS', 'Options'), ('VEHICLE', 'Vehicle'), ('MCU_TR_ENTITY', 'MCU_TR_Entity'), ('MCU_TR_AI_Poi', 'MCU_TR_AI_Poi'), ('MCU_TR_MissionBegin', 'MCU_TR_MissionBegin'), ('MCU_TR_MissionEnd', 'MCU_TR_MissionEnd'), ('MCU_TR_MissionObjective', 'MCU_TR_MissionObjective'), ('MCU_TR_Subtitle', 'MCU_TR_Subtitle'), ('MCU_Activate', 'MCU_Activate'), ('MCU_Deactivate', 'MCU_Deactivate'), ('MCU_Timer', 'MCU_Timer'), ('MCU_Waypoint', 'MCU_Waypoint'), ('MCU_CMD_AttackTarget', 'MCU_CMD_AttackTarget'), ('MCU_CMD_AttackArea', 'MCU_CMD_AttackArea'), ('MCU_CMD_Cover', 'MCU_CMD_Cover'), ('MCU_CMD_Move', 'MCU_CMD_Move')], max_length=100),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('missionobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.missionobject')),
                ('script', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('country', models.PositiveIntegerField()),
                ('number_in_formation', models.PositiveIntegerField()),
                ('vulnerable', models.BooleanField()),
                ('engangeable', models.BooleanField()),
                ('limit_ammo', models.BooleanField()),
                ('ai_level', models.PositiveBigIntegerField()),
                ('coop_start', models.BooleanField()),
                ('fuel', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, "Fuel can't be less than 0"), django.core.validators.MaxValueValidator(100, "Fuel can't be more than 100 %")])),
                ('link_tr_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mission_obj_id', to='core.missionobject')),
            ],
            bases=('core.missionobject',),
        ),
    ]
