# Generated by Django 4.2.7 on 2024-03-10 06:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mission_mission_objects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='mission_objects',
        ),
        migrations.AddField(
            model_name='missionobject',
            name='attached_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_objects', to='core.mission'),
        ),
        migrations.AlterField(
            model_name='missionobject',
            name='object_type',
            field=models.CharField(choices=[('Options', 'Options'), ('Vehicle', 'Vehicle'), ('MCU_TR_Entity', 'MCU_TR_Entity'), ('MCU_TR_AI_Poi', 'MCU_TR_AI_Poi'), ('MCU_TR_MissionBegin', 'MCU_TR_MissionBegin'), ('MCU_TR_MissionEnd', 'MCU_TR_MissionEnd'), ('MCU_TR_MissionObjective', 'MCU_TR_MissionObjective'), ('MCU_TR_Subtitle', 'MCU_TR_Subtitle'), ('MCU_Activate', 'MCU_Activate'), ('MCU_Deactivate', 'MCU_Deactivate'), ('MCU_Timer', 'MCU_Timer'), ('MCU_Waypoint', 'MCU_Waypoint'), ('MCU_CMD_AttackTarget', 'MCU_CMD_AttackTarget'), ('MCU_CMD_AttackArea', 'MCU_CMD_AttackArea'), ('MCU_CMD_Cover', 'MCU_CMD_Cover'), ('MCU_CMD_Move', 'MCU_CMD_Move')], max_length=100),
        ),
        migrations.AlterField(
            model_name='missionobject',
            name='properties',
            field=models.JSONField(blank=True, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('missionobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.missionobject')),
                ('vehicle_type', models.CharField(choices=[('PZ_IV', 'PzKpfw_IV'), ('PZ_V_PANTHER', 'PzKpfw_V_Panther'), ('PZ_VI_TIGER', 'PzKpfw_VI_Tiger'), ('KV_1S', 'KV-1S'), ('SU_152', 'SU-152')], max_length=100)),
                ('script', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('country', models.PositiveIntegerField()),
                ('number_in_formation', models.PositiveIntegerField()),
                ('vulnerable', models.BooleanField()),
                ('engageable', models.BooleanField()),
                ('limit_ammo', models.BooleanField()),
                ('ai_level', models.PositiveBigIntegerField()),
                ('coop_start', models.BooleanField()),
                ('fuel', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, "Fuel can't be less than 0"), django.core.validators.MaxValueValidator(100, "Fuel can't be more than 100 %")])),
                ('link_tr_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_obj_id', to='core.missionobject')),
            ],
            bases=('core.missionobject',),
        ),
    ]
