# Generated by Django 4.2.7 on 2024-02-15 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_missionobject_object_type_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='link_tr_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_obj_id', to='core.missionobject'),
        ),
    ]
