# Generated by Django 4.2.7 on 2024-02-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_vehicle_link_tr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionobject',
            name='properties',
            field=models.JSONField(blank=True, max_length=1024, null=True),
        ),
    ]
