# Generated by Django 4.2.7 on 2024-02-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_missionobject_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('PZ_IV', 'PzKpfw_IV'), ('PZ_V_PANTHER', 'PzKpfw_V_Panther'), ('PZ_VI_TIGER', 'PzKpfw_VI_Tiger'), ('KV_1S', 'KV-1S'), ('SU_152', 'SU-152')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='script',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
