# Generated by Django 4.2.7 on 2024-03-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vehicle_vehicle_type_alter_vehicle_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='engangeable',
            new_name='engageable',
        ),
        migrations.AlterField(
            model_name='missionobject',
            name='object_type',
            field=models.CharField(choices=[('Options', 'Options'), ('Vehicle', 'Vehicle'), ('MCU_TR_Entity', 'MCU_TR_Entity'), ('MCU_TR_AI_Poi', 'MCU_TR_AI_Poi'), ('MCU_TR_MissionBegin', 'MCU_TR_MissionBegin'), ('MCU_TR_MissionEnd', 'MCU_TR_MissionEnd'), ('MCU_TR_MissionObjective', 'MCU_TR_MissionObjective'), ('MCU_TR_Subtitle', 'MCU_TR_Subtitle'), ('MCU_Activate', 'MCU_Activate'), ('MCU_Deactivate', 'MCU_Deactivate'), ('MCU_Timer', 'MCU_Timer'), ('MCU_Waypoint', 'MCU_Waypoint'), ('MCU_CMD_AttackTarget', 'MCU_CMD_AttackTarget'), ('MCU_CMD_AttackArea', 'MCU_CMD_AttackArea'), ('MCU_CMD_Cover', 'MCU_CMD_Cover'), ('MCU_CMD_Move', 'MCU_CMD_Move')], max_length=100),
        ),
    ]
