# Generated by Django 4.2.7 on 2024-03-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_engangeable_vehicle_engageable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='mission_objects',
        ),
        migrations.AddField(
            model_name='missionobject',
            name='attached_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_objects', to='core.mission'),
        ),
    ]
